version: "3.8"
services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: web-app
    ports:
      - 3000:3000
    working_dir: /app/myapp
    volumes:
      - ./frontend:/app
    command: sh -c "npm run dev"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: web-api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./frontend/myapp/.next:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d